version: '2.4'
services:
  nginx:
    container_name: dev-sidecar-nginx
    image: docmirror/dev-sidecar-nginx:1.3.0
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
    - 443:443
    volumes:
    -  /disk02/www:/usr/share/nginx/html
    environment:
    - TZ=Asia/Shanghai
    - SSL_CERTIFICATE=/app/ssl/cert.crt
    - SSL_CERTIFICATE_KEY=/app/ssl/cert.key
    - HOSTNAME=yourdomain.com
    - PASSWORD=123456
    - CONTEXT_PATH=change_me
