version: '2.4'
services:
  nginx:
    container_name: dev-sidecar-nginx
    image: dev-sidecar-nginx:1.0.0
    restart: always
    ports:
    - 443:443
    volumes:
    -  ~/deploy/nginx-proxy/ssl:/app/ssl/  # 证书目录映射
    environment:
    - TZ=Asia/Shanghai
    - SSL_CERTIFICATE=/app/ssl/cert.crt
    - SSL_CERTIFICATE_KEY=/app/ssl/cert.key
    - HOSTNAME=gh-aws.docmirror.top # 修改为你的域名
    - PASSWORD=thankyou # 修改密码
    - CONTEXT_PATH=edfbdtye45ydfsb # 请求路径
